---
extends: default

ignore: |
  .git/
  .github/

rules:
  line-length:
    max: 160
    allow-non-breakable-inline-mappings: true
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
