scrape_configs:
- job_name: myapp
  scrape_interval: 10s
  static_configs:
  # Example of a correct histogram_quantile query:
  # histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))
  # Note: Make sure to send HTTP requests to localhost:4200 to generate data
  - targets:
    - localhost:4200