name: logging
services:
  app:
    build: .
    ports: [4200:4200]
    labels: { logging: "promtail" }

  loki:
    image: grafana/loki:3.3.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes: [./data/loki:/loki]

  promtail:
    image: grafana/promtail:3.3.2
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes:
      - ./configs/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: [loki]

  grafana:
    image: grafana/grafana:11.4.0
    ports: [3000:3000]
    volumes:
      - ./configs/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  prometheus:
    image: prom/prometheus:latest
    ports: [9090:9090]
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
