---
- hosts: all
  remote_user: wbg0x
  become: yes
  become_method: sudo
  vars:
    LOCAL_HOSTNAME: 'wbg0x-private'
    LOCAL_FQDN_NAME: 'private.wbg0x.com'
  tasks:
    - name: Set the timezone for the server to be UTC
      command: ln -sf /usr/share/zoneinfo/UTC /etc/localtime
    - name: Set up a unique hostname
      hostname: name={{ LOCAL_HOSTNAME }}
    - name: Add the server's domain to the hosts file
      lineinfile: dest=/etc/hosts
                  regexp='.*{{ item }}$'
                  line="{{ hostvars[item].ansible_host }} {{ LOCAL_FQDN_NAME }} {{ LOCAL_HOSTNAME }}"
                  state=present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"
    - name: Update packages
      apt: update_cache=yes upgrade=dist
          