---
- name: Common server setup
  hosts: all
  remote_user: wbg0x
  become: true
  become_method: ansible.builtin.sudo
  vars:
    local_hostname: wbg0x-private
    local_fqdn_name: private.wbg0x.com
  tasks:
    - name: Set the timezone for the server to be UTC
      ansible.builtin.command: ln -sf /usr/share/zoneinfo/UTC /etc/localtime
      changed_when: false
    - name: Set up a unique hostname
      ansible.builtin.hostname:
        name: "{{ local_hostname }}"
    - name: Add the server's domain to the hosts file
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: ".*{{ item }}$"
        line: "{{ hostvars[item].ansible_host }} {{ local_fqdn_name }} {{ local_hostname }}"
        state: present
      when: hostvars[item].ansible_host is defined
      loop: "{{ groups.all }}"
    - name: Update packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
