---
- name: Create limited user account
  hosts: all
  remote_user: root
  vars:
    normal_user_name: wbg0x
  tasks:
    - name: Create a secondary, non-root user
      ansible.builtin.user:
        name: "{{ normal_user_name }}"
        password: '$5$wbg0x$lqAoKBlzDEGg/TavS3HqpUfnSD4t3eTt5xrSLkCUtG3'
        shell: /bin/bash
    - name: Add remote authorized key to allow future passwordless logins
      ansible.posix.authorized_key:
        user: "{{ normal_user_name }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: Add normal user to sudoers
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        regexp: "{{ normal_user_name }} ALL"
        line: "{{ normal_user_name }}"
        state: present
