apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: devsecops-boilerplate
  annotations:
    description: Baseline shell exec observability (Monitor mode).
spec:
  kprobes:
    - call: sys_execve
      syscall: true
      args:
        - index: 0
          type: string
      selectors:
        - matchArgs:
            - index: 0
              operator: Prefix
              values:
                - /bin/sh
                - /bin/bash
          matchActions:
            - action: Post
